import React, { useState, useEffect } from 'react';
import { Sparkles, RefreshCw, Feather } from 'lucide-react';
import { articlesApi } from '../api/client';
import ArticleCard from '../components/ArticleCard';
import './HomePage.css';

// Skeleton Component for Loading State
const ArticleSkeleton = () => (
  <div className="skeleton-card">
    <div className="skeleton-icon shimmer"></div>
    <div className="skeleton-title shimmer"></div>
    <div className="skeleton-text shimmer"></div>
    <div className="skeleton-text shimmer"></div>
    <div className="skeleton-text short shimmer"></div>
    <div className="skeleton-footer">
      <div className="skeleton-tag shimmer"></div>
      <div className="skeleton-date shimmer"></div>
    </div>
  </div>
);

const HomePage = () => {
  const [articles, setArticles] = useState([]);
  const [loading, setLoading] = useState(true);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const [error, setError] = useState(null);
  const [lastUpdated, setLastUpdated] = useState(null);

  useEffect(() => {
    fetchArticles({ forceSkeleton: true });
  }, []);

  const fetchArticles = async ({ forceSkeleton = false } = {}) => {
    try {
      const shouldShowSkeleton = forceSkeleton || articles.length === 0;
      setLoading(shouldShowSkeleton);
      setIsRefreshing(!shouldShowSkeleton);
      setError(null);
      const response = await articlesApi.getAll();
      setArticles(response.data);
      setLastUpdated(new Date());
    } catch (err) {
      setError('Unable to load articles. Please check your connection.');
      console.error('Error loading articles:', err);
    } finally {
      setLoading(false);
      setIsRefreshing(false);
    }
  };

  const formatUpdatedLabel = () => {
    if (!lastUpdated) return 'Syncing insights...';
    return `Updated ${lastUpdated.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`;
  };

  const handleRefresh = () => {
    if (isRefreshing) return;
    fetchArticles();
  };

  // Error State
  if (error) {
    return (
      <div className="home-page">
        <div className="container error-container">
          <div className="error-card">
            <h3>Oops!</h3>
            <p className="error-message">{error}</p>
            <button onClick={fetchArticles} className="retry-button">
              <RefreshCw size={18} />
              Try Again
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="home-page">
      <div className="container">
        {/* Header */}
        <header className="page-header">
          <h1>Latest Blog Articles</h1>
          <p className="subtitle">
            Discover the technology articles generated by artificial intelligence!
          </p>
          <div className="header-actions">
            <button
              type="button"
              className={`refresh-button ${isRefreshing ? 'is-loading' : ''}`}
              onClick={handleRefresh}
              disabled={isRefreshing}
            >
              <RefreshCw size={16} />
              <span>{isRefreshing ? 'Refreshing...' : 'Refresh feed'}</span>
            </button>
            <div className="updated-chip">
              <Feather size={14} />
              <span>{formatUpdatedLabel()}</span>
            </div>
          </div>
        </header>

        {isRefreshing && articles.length > 0 && (
          <div className="refresh-indicator">
            Updating cards with new ideas...
          </div>
        )}

        <div className={`articles-grid ${isRefreshing ? 'is-refreshing' : ''}`}>
          {loading ? (
            // Show 6 skeleton loaders while fetching
            Array.from({ length: 6 }).map((_, index) => (
              <ArticleSkeleton key={index} />
            ))
          ) : articles.length === 0 ? (
            <div className="no-articles">
              <p>No articles yet. Check back soon!</p>
            </div>
          ) : (
            // Render actual articles
            articles.map((article, index) => (
              <ArticleCard 
                key={article.id} 
                article={article}
                style={{ animationDelay: `${index * 0.1}s` }}
              />
            ))
          )}
        </div>
      </div>
    </div>
  );
};

export default HomePage;
